services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crypto_watcher
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
volumes:
  db_data: